name: my_freends
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.7
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  toggle_switch: ^2.1.0
  flutter_polyline_points: ^2.0.0
  #yandex_mapkit: ^3.4.0
  dio: ^5.4.1
  yandex_mapkit: ^3.4.0
  geolocator: ^11.0.0
  freezed: ^2.4.7
  gap: ^3.0.1
  zoom_tap_animation: ^1.1.0
  #google_maps_flutter: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 400
        - asset: assets/fonts/Raleway-BlackItalic.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway-ExtraBoldItalic.ttf
          weight: 900
        - asset: assets/fonts/Raleway-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Raleway-ExtraLightItalic.ttf
          weight: 200
        - asset: assets/fonts/Raleway-Italic.ttf
          weight: 300
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 400
        - asset: assets/fonts/Raleway-LightItalic.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 600
        - asset: assets/fonts/Raleway-MediumItalic.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 800
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 900
        - asset: assets/fonts/Raleway-SemiBoldItalic.ttf
          weight: 900
        - asset: assets/fonts/Raleway-Thin.ttf
          weight: 800
        - asset: assets/fonts/Raleway-ThinItalic.ttf
          weight: 700